### ISSUE TITLE
Target [Amelia\Monzo\Contracts\Client] is not instantiable

### ISSUE THREAD

**Issue by nicholaspearson** [ameliaikeda/monzo-php#2]
I get the following error:
```
[Illuminate\Contracts\Container\BindingResolutionException]                                      
Target [Amelia\Monzo\Contracts\Client] is not instantiable while building [Amelia\Monzo\Monzo].
```

When adding:
```
app('Amelia\Monzo\Monzo');
``` 
to `app/Providers/AppServiceProvider.php`

Example of full file:
```
<?php

namespace Monyozo\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
      app('Amelia\Monzo\Monzo');
    }
}
```

**Comment by ameliaikeda** [comment]
I thought I'd replied to this issue via email, but evidently not, whoops.

The API at Monzo is not yet stable, so I halted progress on this API client (it's still `v0` on packagist) until their current account is launched.

Since you're interested, though, I'll finish fixing up the service provider for this package so it's at least easily usable.

The base functionality is there, but auth (actually fetching access tokens, and refreshing existing ones, along with full socialite integration) is not there yet, along with setup. That's why the tests in the repo only actually test auth with existing tokens + regular routes.

**Comment by nicholaspearson** [comment]
Thank You :)

I temporarily got around this by doing this within my User model:

```php
    public function monzo()
    {
      $client = new \Amelia\Monzo\Client(new Guzzle(), env('MONZO_CLIENT_ID'), env('MONZO_CLIENT_SECRET'));

      $monzo = new \Amelia\Monzo\Monzo($client);

      return $monzo->as($this);
    }
```

With this work around refreshing the tokens seems to be working :)

Maybe this will help with the implementation.
